### ISSUE TITLE
[bug] Rest Api not starting

### ISSUE THREAD

**Issue by hazre** [Remora/Remora.Neos.Headless#10]
This is the error message I get:

```
[ERROR][NeosModLoader] mod Headless REST API from C:\Users\haz\dev\neos-headless\nml_mods\Remora.Neos.Headless.API.Mod.dll threw error from OnEngineInit():
System.MissingMethodException: Method not found: 'Void Grapevine.RestServerBuilder.set_ConfigureServices(System.Action`1<Microsoft.Extensions.DependencyInjection.IServiceCollection>)'.
   at Remora.Neos.Headless.API.Mod.HeadlessApiMod.OnEngineInit()
   at NeosModLoader.ModLoader.HookMod(LoadedNeosMod mod)
        Reading settings file
        Performing version checks and updates, loaded version: 8
```

**Comment by Nihlus** [comment]
Interesting. Are you certain you included all files from the mod into the libs folder (except the mod itself, of course)?

**Comment by hazre** [comment]
Yes I pretty much copy and pasted all the folders inside my neos root. I actually ran into this issue while I was trying to modify the code a bit and ran into this issue after building. I thought it might be issue with the build but then I tried the provided binaries and still same result.

**Comment by Nihlus** [comment]
Have you installed any other mods after this one?

**Comment by hazre** [comment]
No it's a fresh headless install running on windows. I haven't tried on Linux yet but I will once it works

**Comment by Nihlus** [comment]
Since it's Windows, there might be some issues with the GAC being in play... could you try extracting the libraries from the mod into the same directory as Neos.exe instead? I recommend making a backup of the installation beforehand, too.
